export const staticText = {
  loginHeader: 'Let’s you in',
  fbButtonText: 'Continue with Facebook',
  googleButtonText: 'Continue with Google',
  appleButtonText: 'Continue with Apple',
  or: 'or',
  passText: 'Sign in with password',
  doNotAccount: 'Don’t have an account?',
  signUpText: 'Sign up',
  header: `Create Your ${'\n'}Account`,
  loginHeaderWithForgot: 'Login to your Account',
  rememberMe: 'Remember me',
  signUp: 'Sign up',
  signin: 'Sign in',
  continueWith: 'or continue with',
  alreadyAccount: 'Already have an account?',
  SignIn: 'Sign in',
  fillProfile: 'Fill Your Profile',
  continue: 'Continue',
};
